name: bookworm_friends
description: A social reading tracker app.
publish_to: "none"
version: 2.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  supabase_flutter: ^2.8.0
  flutter_riverpod: ^2.6.0
  intl: ^0.20.2
  flutter_easyloading: ^3.0.5
  phosphor_flutter: ^2.1.0
  emojis: ^0.9.9
  animated_text_kit: ^4.2.2
  shimmer: ^3.0.0
  flutter_svg: ^2.0.10
  url_launcher: ^6.3.0
  firebase_core: ^3.3.0
  firebase_messaging: ^15.0.0
  flutter_local_notifications: ^17.0.0
  app_links: ^6.3.0
  in_app_review: ^2.0.9
  package_info_plus: ^8.0.0
  firebase_analytics: ^11.2.0
  firebase_crashlytics: ^4.0.0
  app_tracking_transparency: ^2.0.6
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  shared_preferences: ^2.3.0

dependency_overrides:
  path_provider_foundation: 2.4.1
  shared_preferences_foundation: 2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/bookwormIcon.svg
    - assets/icons/smileBookwormIcon.svg
    - assets/icons/appleWhiteIcon.svg
    - assets/icons/appleBlackIcon.svg
    - assets/icons/googleIcon.svg
    - assets/icons/bookmarkIcon.svg
    - assets/icons/sadCharacter.svg
  fonts:
    - family: DesignHouse
      fonts:
        - asset: assets/fonts/designhouseOTFBold.otf
          weight: 700
        - asset: assets/fonts/designhouseOTFLight.otf
          weight: 300
