// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSPe8c4w7mxSIruhRVShCJrptovJcpWkw',
    appId: '1:212723580252:web:7f3360752e2deedd30d599',
    messagingSenderId: '212723580252',
    projectId: 'bookworm-friends-notification',
    authDomain: 'bookworm-friends-notification.firebaseapp.com',
    storageBucket: 'bookworm-friends-notification.firebasestorage.app',
    measurementId: 'G-36WFVPD0PX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPmt9ERLRxkTVeSXOSxDTUwN2352BIS68',
    appId: '1:212723580252:android:85b17eb6ce76189230d599',
    messagingSenderId: '212723580252',
    projectId: 'bookworm-friends-notification',
    storageBucket: 'bookworm-friends-notification.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2OuS4qswOPWEjdp1km7k-gErNHqwlcgI',
    appId: '1:212723580252:ios:1f2e606f1b79146530d599',
    messagingSenderId: '212723580252',
    projectId: 'bookworm-friends-notification',
    storageBucket: 'bookworm-friends-notification.firebasestorage.app',
    iosBundleId: 'com.unicorn.bookwormFriends',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2OuS4qswOPWEjdp1km7k-gErNHqwlcgI',
    appId: '1:212723580252:ios:9454c984b663f10630d599',
    messagingSenderId: '212723580252',
    projectId: 'bookworm-friends-notification',
    storageBucket: 'bookworm-friends-notification.firebasestorage.app',
    iosBundleId: 'com.example.bookwormFriends',
  );
}
